---
# Specify the parameters that will be used to query CED
#  zone: The name of a CED zone
#  types: A list of types to query. Can simply use BeamElem or LineElem and rely on CED inheritance
#  properties: a list of properties to fetch in addition to default EPICSName and S which are hard-coded.
#              must be applicable to all retrieved types.
#  expressions: a list of CED property expressions.  For example S >= 6.65657 to skip over elements in the
#               injector zone in front of MFA0I03.
ced:
  zone: "Injector"
  types: ["LineElem"]
  properties: []
  expressions:
    - S >= 6.65657

# Classify CED element types as setpoints and readbacks as well
# as specifying which EPICS records are desired for each type.
nodes:
  setpoints:
    Corrector: [".BDL", ".S"]
    Dipole: [".BDL", ".S"]
    Quad: [".BDL", ".S"]
    Solenoid: [".BDL", ".S"]
    CryoCavity: ['PSET','GSET','XPSET8']  # Note XPSET8 requires special handling (belongs zone, not cavity)
  readbacks:
    # BeamLossMonitor: [".Lc"]  # Doesn't work
    BPM: [".XPOS", ".YPOS", ""] # The "" is to give us a bare EPICSName which means the wire sum
    # Inconsistent EPICSName
    # IBC0L02 : IBC0L02Current
    # SBC0R08: has no EPICSName
    # BCM: ["Current"]                   # EPICSName is actually full-blown IBC0L02Current

# Specify the date range for which data should be retrieved from the archiver
# as well as the desired interval within the date range at which graph data
# should be generated.
mya:
  begin: "2021-11-01"
  end: "2021-11-02"
  interval: "1h"
  filters:
    - "IBC0R08CRCUR1 > 0.1"
  # Make sure any PVs mentioned in filters are also included in the global list
  global:
    - ISD0I011G
    - BOOMHLAMODE
    - BOOMHLBMODE
    - BOOMHLCMODE
    - BOOMHLDMODE
    - IBC0R08CRCUR1
    - IBC1H04CRCUR2
    - IBC2C24CRCUR3
    - IBC3H00CRCUR4
    - IBCAD00CRCUR6
    - IGL1I00BEAMODE
    - IGL1I00HALLAMODE
    - IGL1I00HALLBMODE
    - IGL1I00HALLCMODE
    - IGL1I00HALLDMODE
# Parameters for defining edges.
edges:
  connectivity: 2
  weighted: true
  directed: false

